HEARTHSTONE_POWER_LOG_PATH = "D:/战网/Hearthstone/Logs/Power.log"

# 关于信息打印的设置
DEBUG_PRINT = False
WARNING_PRINT = True
SYS_PRINT = True
INFO_PRINT = True
ERROR_PRINT = True

# 把鼠标移到卡牌上到试图截图所需的时间
CARD_APPEAR_INTERVAL = 0.02
STEP = [0, 0, 140, 139, 131, 105, 88, 75, 66, 58, 52]
START = [0, 819, 749, 679, 622, 608, 599, 593, 588, 585, 582]

FSM_CHOOSINGHERO = "ChoosingHero"
FSM_MATCHING = "Matching"
FSM = "ChoosingCard"
FSM_NOTMYTURN = "NotMyTurn"
FSM_MYTURN = "MyTurn"
FSM_LEAVEHS = "LeaveHS"
FSM_MAIN_MENU = "MainMenu"

LOG_CONTAINER_ERROR = 0
LOG_CONTAINER_INFO = 1

LOG_LINE_CREATE_GAME = 0
LOG_LINE_GAME_ENTITY = 1
LOG_LINE_PLAYER_ENTITY = 2
LOG_LINE_FULL_ENTITY = 3
LOG_LINE_SHOW_ENTITY = 4
LOG_LINE_BLOCK_START = 5
LOG_LINE_BLOCK_END = 6
LOG_LINE_PLAYER_ID = 7
LOG_LINE_TAG_CHANGE = 8



FRONT_ROPING_TIME = 1.5
BACK_ROPING_TIME = 1
STATE_CHECK_INTERVAL = 1
EMOJ_RATE = 0.08
IF_PRINTOUT = 1
OPERATE_INTERVAL = 0.2
SMALL_OPERATE_INTERVAL = 0.1
BASIC_MINION_PUT_INTERVAL = 2

CARD_SPELL = 0
CARD_MINION = 1
CARD_WEAPON = 2
SPELL_NO_POINT = 0
SPELL_POINT_OPPO = 1
SPELL_POINT_MINE = 2
