# 你的Power.log的路径, 应该在你的炉石安装目录下的`Logs/`文件夹中, 这里放的是我的路径
# ** 一定要修改成自己电脑上的路径 **
HEARTHSTONE_POWER_LOG_PATH = "D:/战网/Hearthstone/Logs/Power.log"

# 你的炉石用户名, 注意英文标点符号, 把后面的数字也带上
YOUR_NAME = "ChangeThis#54321"

# 关于信息打印的设置
DEBUG_PRINT = True
WARNING_PRINT = True
SYS_PRINT = True
INFO_PRINT = True
ERROR_PRINT = True

FRONT_ROPING_TIME = 1.5
BACK_ROPING_TIME = 1
STATE_CHECK_INTERVAL = 1
EMOJ_RATE = 0.15
IF_PRINTOUT = 1
OPERATE_INTERVAL = 0.2
SMALL_OPERATE_INTERVAL = 0.1
BASIC_MINION_PUT_INTERVAL = 1.2

# 把鼠标移到卡牌上到试图截图所需的时间
CARD_APPEAR_INTERVAL = 0.02
STEP = [0, 0, 140, 139, 131, 105, 88, 75, 66, 58, 52]
START = [0, 819, 749, 679, 622, 608, 599, 593, 588, 585, 582]

FSM_LEAVE_HS = "Leave Hearth Stone"
FSM_MAIN_MENU = "Main Menu"
FSM_CHOOSING_HERO = "Choosing Hero"
FSM_MATCHING = "Match Opponent"
FSM_CHOOSING_CARD = "Choosing Card"
# FSM_NOT_MY_TURN = "Not My Turn"
# FSM_MY_TURN = "My Turn"
FSM_BATTLING = "Battling"
FSM_ERROR = "ERROR"
FSM_QUITTING_BATTLE = "QUITTING BATTLE"

LOG_CONTAINER_ERROR = 0
LOG_CONTAINER_INFO = 1

LOG_LINE_CREATE_GAME = "Create Game"
LOG_LINE_GAME_ENTITY = "Create Game Entity"
LOG_LINE_PLAYER_ENTITY = "Create Player Entity"
LOG_LINE_FULL_ENTITY = "Full Entity"
LOG_LINE_SHOW_ENTITY = "Show Entity"
LOG_LINE_CHANGE_ENTITY = "Change Entity"
LOG_LINE_BLOCK_START = "Block Start"
LOG_LINE_BLOCK_END = "Block End"
LOG_LINE_PLAYER_ID = "Player ID"
LOG_LINE_TAG_CHANGE = "Tag Change"
LOG_LINE_TAG = "Tag"

CARD_BASE = "BASE"
CARD_SPELL = "SPELL"
CARD_MINION = "MINION"
CARD_WEAPON = "WEAPON"
CARD_HERO = "HERO"
CARD_HERO_POWER = "HERO_POWER"
CARD_ENCHANTMENT = "ENCHANTMENT"

SPELL_NO_POINT = 0
SPELL_POINT_OPPO = 1
SPELL_POINT_MINE = 2
